### ISSUE TITLE
Trying to use AzApi to create Bastion Host Shareable link, but getting "The requested resource does not support http method 'GET'"

### ISSUE THREAD

**Issue by LeeorV** [Azure/terraform-provider-azapi#218]
After messing around with the azapi provider a bit, to try and get it to call the correct API endpoint (for this API: 
Create: https://learn.microsoft.com/en-us/rest/api/virtualnetwork/put-bastion-shareable-link/put-bastion-shareable-link?tabs=HTTP#code-try-0
Delete: https://learn.microsoft.com/en-us/rest/api/virtualnetwork/delete-bastion-shareable-link/delete-bastion-shareable-link?tabs=HTTP
Get: https://learn.microsoft.com/en-us/rest/api/virtualnetwork/get-bastion-shareable-link/get-bastion-shareable-link?tabs=HTTP

I managed to arrive at the below: 
```terraform
resource "azapi_resource" "bastion_shareable_link" {
  type              = "Microsoft.Network/bastionHosts@2022-05-01"
  name              = "${azurerm_bastion_host.bastion_host.name}/createShareableLinks"
  parent_id         = azurerm_resource_group.rg.id
 location          = azurerm_bastion_host.bastion_host.location
  schema_validation_enabled = false

  body = jsonencode(
    {
        "vms" = [
            { "vm" = {"id" = "${azurerm_windows_virtual_machine.my-win2016-vm.id}"} }
            ]
    })

  tags = {
    "name" = "MyVMLink"
  }

  response_export_values = ["*"]
}
```
However because this api endpoint is specifically for creating the link, I get "Message": "The requested resource does not support http method 'GET'." as an error. 

is there anyway to get this API working wtih azapi?

**Comment by ms-henglu** [comment]
Hi @LeeorV ,

Thank you for taking time to report this issue!

The documents are about resource's actions instead of resources, so please use `azapi_resource_action` resource/data source for this API. I made the following example, hope it can help you, :)

```hcl

locals {
  create_link = true
}

resource "azapi_resource_action" "create_link" {
  type        = "Microsoft.Network/bastionHosts@2022-05-01"
  resource_id = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/bastionHosts/{bastionHostName}"
  action      = "createShareableLinks"
  body = jsonencode({
    vms = [
      {
        vm = {
          id = azurerm_windows_virtual_machine.my-win2016-vm.id
        }
      }
    ]
  })

  count = local.create_link ? 1 : 0
}

resource "azapi_resource_action" "delete_link" {
  type        = "Microsoft.Network/bastionHosts@2022-05-01"
  resource_id = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/bastionHosts/{bastionHostName}"
  action      = "deleteShareableLinks"
  body = jsonencode({
    vms = [
      {
        vm = {
          id = azurerm_windows_virtual_machine.my-win2016-vm.id
        }
      }
    ]
  })


  count = !local.create_link ? 1 : 0
}

data "azapi_resource_action" "test" {
  type                   = "Microsoft.Network/bastionHosts@2022-05-01"
  resource_id            = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/bastionHosts/{bastionHostName}"
  action                 = "getShareableLinks"
  response_export_values = ["*"]
}

```

**Comment by LeeorV** [comment]
Hi @ms-henglu , thank you very muchc for the informative reply and example. 

I was able to get the "Create Shareable Link" and "Delete Shareable Link" options to work. 

However I am struggling with getting the "Get Shareable Link" data resource to work - I keep getting an error of 
"│ Error: performing action getShareableLinks of "Resource: (ResourceId \"/subscriptions/f04c6287-c03b-4749-8653-16dc17227018/resourceGroups/Torque-Env-RG-bv2n5dzvja13z1/providers/Microsoft.Network/bastionHosts/Torque-Az-Bastion\" / Api Version \"2022-05-01\")": the response did not contain a status"

This is my data resource: (I tried it with an empty body too, and got the same result, I've confirmed the correct end point is reached and that the resource id is the same as the commented out string below it). 
data "azapi_resource_action" "get_link" {
  type                   = "Microsoft.Network/bastionHosts@2022-05-01"
  resource_id = azurerm_bastion_host.bastion_host.id
#  resource_id            = "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/bastionHosts/{bastionHostName}"
#  resource_id            = "/subscriptions/f04c6287-c03b-4749-8653-16dc17227018/resourceGroups/Torque-Env-RG-bv2n5dzvja13z1/providers/Microsoft.Network/bastionHosts/Torque-Az-Bastion"
  action                 = "getShareableLinks"
  response_export_values = ["*"]
  body = jsonencode({
    vms = [
      {
        vm = {
          id = azurerm_windows_virtual_machine.my-win2016-vm.id
        }
      }
    ]
  })
 }


Any help will be immensely appreciated, I need this to work for a customer POC we're running that includes provisioning a Bastion host with a shareable link and retrieving that link via terraform as part of its content.

**Comment by LeeorV** [comment]
Hello again @ms-henglu, 

Thank you very much for this confirmation! any idea why this doesn't come up when testing this endpoint through it's test page? 
https://learn.microsoft.com/en-us/rest/api/virtualnetwork/get-bastion-shareable-link/get-bastion-shareable-link?tabs=HTTP&tryIt=true&source=docs#code-try-0
I can see in my Chrome browser's "Network" development tool when capturing the API request, that it did indeed return a status code of 200, as also indicated by the test page's response section: 

**Request:**
```YAML
POST https://management.azure.com/subscriptions/f04c6287-c03b-4749-8653-16dc17227018/resourceGroups/Torque-Env-RG-bv2n5dzvja13z1/providers/Microsoft.Network/bastionHosts/Torque-Az-Bastion/getShareableLinks?api-version=2022-05-01
Authorization: Bearer (auth token)
Content-type: application/json
```

**Response:**
```YAML
azure-asyncnotification: Enabled
azure-asyncoperation: https://management.azure.com/subscriptions/f04c6287-c03b-4749-8653-16dc17227018/providers/Microsoft.Network/locations/westus2/operations/07c2046a-d0a1-49e9-a8ed-85ca0e369f7a?api-version=2022-05-01
cache-control: no-cache
content-type: application/json; charset=utf-8
date: Tue, 08 Nov 2022 08:19:01 GMT
expires: -1
location: https://management.azure.com/subscriptions/f04c6287-c03b-4749-8653-16dc17227018/providers/Microsoft.Network/locations/westus2/operationResults/07c2046a-d0a1-49e9-a8ed-85ca0e369f7a?api-version=2022-05-01
pragma: no-cache
retry-after: 10
server: Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0
strict-transport-security: max-age=31536000; includeSubDomains
x-ms-arm-service-request-id: bb0864b2-55d8-4286-97e3-7f6eb1d43012
x-ms-correlation-request-id: e1fb404a-5d19-4c91-b6d5-0d839114b478
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-request-id: 07c2046a-d0a1-49e9-a8ed-85ca0e369f7a
x-ms-routing-request-id: FRANCESOUTH:20221108T081901Z:e1fb404a-5d19-4c91-b6d5-0d839114b478
```
