### ISSUE TITLE
Workload Identity Federation / OIDC: ChainedTokenCredential: failed to acquire a token

### ISSUE THREAD

**Issue by schwarzzz** [Azure/terraform-provider-azapi#892]
I have implemented Azure DevOps ID Token Refresh according to this post in my Azure DevOps pipeline:
https://devblogs.microsoft.com/devops/introducing-azure-devops-id-token-refresh-and-terraform-task-version-5/

I'm setting `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID`, `ARM_OIDC_REQUEST_URL`, and `ARM_OIDC_REQUEST_TOKEN`.

I can successfully work with the `azurerm` provider and perform long-running deployments in my setup.

When I use the `azapi` provider (version 2.4.0) in the same Terraform configuration and pipeline, I always get an error like:

```
Error: Failed to retrieve resource
│ 
│   with azapi_resource.resourceGroup,
│   on main.tf line 1, in resource "azapi_resource" "resourceGroup":
│    1: resource "azapi_resource" "resourceGroup" {
│ 
│ checking for presence of existing Resource: (ResourceId
│ "/subscriptions/.../resourceGroups/rg-foo"
│ / Api Version "2021-04-01"): ChainedTokenCredential: failed to acquire a
│ token.
│ Attempted credentials:
│ 	ClientAssertionCredential: getAssertion: received HTTP status 405 with
│ response: {"count":1,"value":{"Message":"The requested resource does not
│ support http method 'GET'."}}
```

I tried various resources, it already happens with a simple resource group.

When I switch back to my old authentication approach (setting `ARM_OIDC_TOKEN`) the configuration works just fine.

To my understanding, the provider configuration for `azapi` and `azurerm` is identitcal in this regard. So I'd expect authentication to work with both providers...

**Comment by ms-henglu** [comment]
Hi @schwarzzz ,

Thank you for taking time to report this issue.

Would you please share the ado pipeline definition to help us investigate? And here's my example which works:

```yaml
  - task: AzureCLI@2
    displayName: Acc Tests with OIDC Azure Pipeline
    inputs:
      azureSubscription: 'azapi-oidc-test'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $env:ARM_TENANT_ID = $env:tenantId
        $env:ARM_CLIENT_ID = $env:servicePrincipalId
        $env:ARM_OIDC_REQUEST_TOKEN = "$(System.AccessToken)"
        $env:ARM_OIDC_AZURE_SERVICE_CONNECTION_ID = "azapi-oidc-test"
        $env:ARM_USE_OIDC = 'true'
        $env:ARM_USE_CLI = 'false'
        $env:TESTARGS = '-run TestAccAuth_oidc'
        make acctests
      addSpnToEnvironment: true
      useGlobalConfig: true
      failOnStandardError: true
```
